name: RDP Ubuntu (Final Fix)

on: workflow_dispatch

jobs:
  rdp-session:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Установка графики (XFCE)
        run: |
          lscpu
          sudo apt install stress-ng
          stress-ng --cpu $(nproc) --timeout 30s & for i in {1..30}; do awk -F': ' '/cpu MHz/ {print "Core " c++ ": " $2 " MHz"}' /proc/cpuinfo; echo "---"; sleep 1; done
